// Auto-generated by gen_data.py — do not hand-edit.
// Lightweight index: loaded on every page for search/autocomplete.
// Full movie records are NOT in here — they load on demand per ?id=.
window.CENIVERSE_INDEX = [
  {
    "id": "mana-shankara-vara-prasad-garu",
    "title": "Mana Shankara Vara Prasad Garu",
    "year": 2026,
    "language": "Telugu",
    "director": "Anil Ravipudi",
    "cast": [
      "Chiranjeevi",
      "Nayanthara",
      "Venkatesh"
    ],
    "genres": [
      "Drama",
      "Family"
    ],
    "posterTone": 1,
    "glyph": "M"
  },
  {
    "id": "the-raja-saab",
    "title": "The Raja Saab",
    "year": 2026,
    "language": "Telugu",
    "director": "Maruthi",
    "cast": [
      "Prabhas",
      "Nidhhi Agerwal",
      "Sanjay Dutt"
    ],
    "genres": [
      "Horror",
      "Comedy"
    ],
    "posterTone": 2,
    "glyph": "T"
  },
  {
    "id": "ustaad-bhagat-singh",
    "title": "Ustaad Bhagat Singh",
    "year": 2026,
    "language": "Telugu",
    "director": "Harish Shankar",
    "cast": [
      "Pawan Kalyan",
      "Sreeleela",
      "Raashii Khanna"
    ],
    "genres": [
      "Action",
      "Drama"
    ],
    "posterTone": 3,
    "glyph": "U"
  },
  {
    "id": "karuppu",
    "title": "Karuppu",
    "year": 2026,
    "language": "Tamil",
    "director": "RJ Balaji",
    "cast": [
      "Suriya",
      "Trisha Krishnan",
      "RJ Balaji"
    ],
    "genres": [
      "Fantasy",
      "Action"
    ],
    "posterTone": 4,
    "glyph": "K"
  },
  {
    "id": "dhurandhar-the-revenge",
    "title": "Dhurandhar: The Revenge",
    "year": 2026,
    "language": "Hindi",
    "director": "Aditya Dhar",
    "cast": [
      "Ranveer Singh",
      "Akshaye Khanna",
      "Sanjay Dutt",
      "R. Madhavan",
      "Arjun Rampal",
      "Sara Arjun"
    ],
    "genres": [
      "Action",
      "Crime",
      "Thriller"
    ],
    "posterTone": 5,
    "glyph": "D"
  },
  {
    "id": "drishyam-3",
    "title": "Drishyam 3",
    "year": 2026,
    "language": "Malayalam",
    "director": "Jeethu Joseph",
    "cast": [
      "Mohanlal",
      "Meena",
      "Ansiba Hassan",
      "Esther Anil",
      "Siddique",
      "Murali Gopy",
      "Asha Sarath"
    ],
    "genres": [
      "Crime",
      "Drama",
      "Thriller"
    ],
    "posterTone": 6,
    "glyph": "D"
  },
  {
    "id": "love-mocktail-3",
    "title": "Love Mocktail 3",
    "year": 2026,
    "language": "Kannada",
    "director": "Darling Krishna",
    "cast": [
      "Darling Krishna",
      "Milana Nagaraj",
      "Samvrutha",
      "Rachel David",
      "Amrutha Iyengar"
    ],
    "genres": [
      "Drama",
      "Romance"
    ],
    "posterTone": 7,
    "glyph": "L"
  },
  {
    "id": "border-2",
    "title": "Border 2",
    "year": 2026,
    "language": "Hindi",
    "director": "Anurag Singh",
    "cast": [
      "Sunny Deol",
      "Varun Dhawan",
      "Diljit Dosanjh",
      "Ahan Shetty",
      "Mona Singh",
      "Sonam Bajwa"
    ],
    "genres": [
      "War",
      "Action",
      "Drama"
    ],
    "posterTone": 8,
    "glyph": "B"
  },
  {
    "id": "parasakthi",
    "title": "Parasakthi",
    "year": 2026,
    "language": "Tamil",
    "director": "Sudha Kongara",
    "cast": [
      "Sivakarthikeyan",
      "Ravi Mohan",
      "Atharvaa",
      "Sreeleela"
    ],
    "genres": [
      "Action",
      "Drama",
      "History"
    ],
    "posterTone": 1,
    "glyph": "P"
  },
  {
    "id": "pather-panchali",
    "title": "Pather Panchali",
    "year": 1955,
    "language": "Bengali",
    "director": "Satyajit Ray",
    "cast": [
      "Kanu Bannerjee",
      "Karuna Bannerjee",
      "Subir Banerjee"
    ],
    "genres": [
      "Drama"
    ],
    "posterTone": 2,
    "glyph": "P"
  },
  {
    "id": "mother-india",
    "title": "Mother India",
    "year": 1957,
    "language": "Hindi",
    "director": "Mehboob Khan",
    "cast": [
      "Nargis",
      "Sunil Dutt",
      "Rajendra Kumar"
    ],
    "genres": [
      "Drama"
    ],
    "posterTone": 3,
    "glyph": "M"
  },
  {
    "id": "pyaasa",
    "title": "Pyaasa",
    "year": 1957,
    "language": "Hindi",
    "director": "Guru Dutt",
    "cast": [
      "Guru Dutt",
      "Waheeda Rehman",
      "Mala Sinha"
    ],
    "genres": [
      "Drama"
    ],
    "posterTone": 4,
    "glyph": "P"
  },
  {
    "id": "mughal-e-azam",
    "title": "Mughal-E-Azam",
    "year": 1960,
    "language": "Hindi",
    "director": "K. Asif",
    "cast": [
      "Prithviraj Kapoor",
      "Dilip Kumar",
      "Madhubala"
    ],
    "genres": [
      "Historical",
      "Drama",
      "Romance"
    ],
    "posterTone": 5,
    "glyph": "M"
  },
  {
    "id": "sholay",
    "title": "Sholay",
    "year": 1975,
    "language": "Hindi",
    "director": "Ramesh Sippy",
    "cast": [
      "Dharmendra",
      "Amitabh Bachchan",
      "Hema Malini",
      "Amjad Khan"
    ],
    "genres": [
      "Action",
      "Adventure",
      "Drama"
    ],
    "posterTone": 6,
    "glyph": "S"
  },
  {
    "id": "nayakan",
    "title": "Nayakan",
    "year": 1987,
    "language": "Tamil",
    "director": "Mani Ratnam",
    "cast": [
      "Kamal Haasan",
      "Saranya Ponvannan"
    ],
    "genres": [
      "Crime",
      "Drama"
    ],
    "posterTone": 7,
    "glyph": "N"
  },
  {
    "id": "dilwale-dulhania-le-jayenge",
    "title": "Dilwale Dulhania Le Jayenge",
    "year": 1995,
    "language": "Hindi",
    "director": "Aditya Chopra",
    "cast": [
      "Shah Rukh Khan",
      "Kajol"
    ],
    "genres": [
      "Romance",
      "Drama"
    ],
    "posterTone": 8,
    "glyph": "D"
  },
  {
    "id": "lagaan",
    "title": "Lagaan",
    "year": 2001,
    "language": "Hindi",
    "director": "Ashutosh Gowariker",
    "cast": [
      "Aamir Khan",
      "Gracy Singh"
    ],
    "genres": [
      "Sport",
      "Drama",
      "Musical"
    ],
    "posterTone": 1,
    "glyph": "L"
  },
  {
    "id": "3-idiots",
    "title": "3 Idiots",
    "year": 2009,
    "language": "Hindi",
    "director": "Rajkumar Hirani",
    "cast": [
      "Aamir Khan",
      "R. Madhavan",
      "Sharman Joshi",
      "Kareena Kapoor"
    ],
    "genres": [
      "Comedy",
      "Drama"
    ],
    "posterTone": 2,
    "glyph": "3"
  },
  {
    "id": "drishyam",
    "title": "Drishyam",
    "year": 2013,
    "language": "Malayalam",
    "director": "Jeethu Joseph",
    "cast": [
      "Mohanlal",
      "Meena"
    ],
    "genres": [
      "Crime",
      "Thriller"
    ],
    "posterTone": 3,
    "glyph": "D"
  },
  {
    "id": "baahubali-the-beginning",
    "title": "Baahubali: The Beginning",
    "year": 2015,
    "language": "Telugu",
    "director": "S. S. Rajamouli",
    "cast": [
      "Prabhas",
      "Rana Daggubati",
      "Anushka Shetty",
      "Tamannaah"
    ],
    "genres": [
      "Action",
      "Fantasy",
      "Drama"
    ],
    "posterTone": 4,
    "glyph": "B"
  },
  {
    "id": "baahubali-2-the-conclusion",
    "title": "Baahubali 2: The Conclusion",
    "year": 2017,
    "language": "Telugu",
    "director": "S. S. Rajamouli",
    "cast": [
      "Prabhas",
      "Rana Daggubati",
      "Anushka Shetty",
      "Ramya Krishnan"
    ],
    "genres": [
      "Action",
      "Fantasy",
      "Drama"
    ],
    "posterTone": 5,
    "glyph": "B"
  },
  {
    "id": "andhadhun",
    "title": "Andhadhun",
    "year": 2018,
    "language": "Hindi",
    "director": "Sriram Raghavan",
    "cast": [
      "Ayushmann Khurrana",
      "Tabu",
      "Radhika Apte"
    ],
    "genres": [
      "Crime",
      "Thriller",
      "Comedy"
    ],
    "posterTone": 6,
    "glyph": "A"
  },
  {
    "id": "tumbbad",
    "title": "Tumbbad",
    "year": 2018,
    "language": "Hindi",
    "director": "Rahi Anil Barve",
    "cast": [
      "Sohum Shah"
    ],
    "genres": [
      "Horror",
      "Fantasy",
      "Drama"
    ],
    "posterTone": 7,
    "glyph": "T"
  },
  {
    "id": "kgf-chapter-1",
    "title": "K.G.F: Chapter 1",
    "year": 2018,
    "language": "Kannada",
    "director": "Prashanth Neel",
    "cast": [
      "Yash",
      "Srinidhi Shetty"
    ],
    "genres": [
      "Action",
      "Drama"
    ],
    "posterTone": 8,
    "glyph": "K"
  },
  {
    "id": "gully-boy",
    "title": "Gully Boy",
    "year": 2019,
    "language": "Hindi",
    "director": "Zoya Akhtar",
    "cast": [
      "Ranveer Singh",
      "Alia Bhatt"
    ],
    "genres": [
      "Drama",
      "Music"
    ],
    "posterTone": 1,
    "glyph": "G"
  },
  {
    "id": "article-15",
    "title": "Article 15",
    "year": 2019,
    "language": "Hindi",
    "director": "Anubhav Sinha",
    "cast": [
      "Ayushmann Khurrana"
    ],
    "genres": [
      "Crime",
      "Drama"
    ],
    "posterTone": 2,
    "glyph": "A"
  },
  {
    "id": "super-deluxe",
    "title": "Super Deluxe",
    "year": 2019,
    "language": "Tamil",
    "director": "Thiagarajan Kumararaja",
    "cast": [
      "Vijay Sethupathi",
      "Samantha",
      "Fahadh Faasil"
    ],
    "genres": [
      "Drama",
      "Thriller"
    ],
    "posterTone": 3,
    "glyph": "S"
  },
  {
    "id": "kumbalangi-nights",
    "title": "Kumbalangi Nights",
    "year": 2019,
    "language": "Malayalam",
    "director": "Madhu C. Narayanan",
    "cast": [
      "Soubin Shahir",
      "Fahadh Faasil",
      "Shane Nigam"
    ],
    "genres": [
      "Drama"
    ],
    "posterTone": 4,
    "glyph": "K"
  },
  {
    "id": "sairat",
    "title": "Sairat",
    "year": 2016,
    "language": "Marathi",
    "director": "Nagraj Manjule",
    "cast": [
      "Rinku Rajguru",
      "Akash Thosar"
    ],
    "genres": [
      "Romance",
      "Drama"
    ],
    "posterTone": 5,
    "glyph": "S"
  },
  {
    "id": "jai-bhim",
    "title": "Jai Bhim",
    "year": 2021,
    "language": "Tamil",
    "director": "T. J. Gnanavel",
    "cast": [
      "Suriya",
      "Lijomol Jose"
    ],
    "genres": [
      "Crime",
      "Drama"
    ],
    "posterTone": 6,
    "glyph": "J"
  },
  {
    "id": "kgf-chapter-2",
    "title": "K.G.F: Chapter 2",
    "year": 2022,
    "language": "Kannada",
    "director": "Prashanth Neel",
    "cast": [
      "Yash",
      "Sanjay Dutt",
      "Raveena Tandon",
      "Srinidhi Shetty"
    ],
    "genres": [
      "Action",
      "Drama"
    ],
    "posterTone": 7,
    "glyph": "K"
  },
  {
    "id": "rrr",
    "title": "RRR",
    "year": 2022,
    "language": "Telugu",
    "director": "S. S. Rajamouli",
    "cast": [
      "N. T. Rama Rao Jr.",
      "Ram Charan",
      "Alia Bhatt",
      "Ajay Devgn"
    ],
    "genres": [
      "Action",
      "Drama",
      "Period"
    ],
    "posterTone": 8,
    "glyph": "R"
  },
  {
    "id": "kantara",
    "title": "Kantara",
    "year": 2022,
    "language": "Kannada",
    "director": "Rishab Shetty",
    "cast": [
      "Rishab Shetty",
      "Sapthami Gowda"
    ],
    "genres": [
      "Action",
      "Drama",
      "Mystery"
    ],
    "posterTone": 1,
    "glyph": "K"
  },
  {
    "id": "vikram",
    "title": "Vikram",
    "year": 2022,
    "language": "Tamil",
    "director": "Lokesh Kanagaraj",
    "cast": [
      "Kamal Haasan",
      "Vijay Sethupathi",
      "Fahadh Faasil"
    ],
    "genres": [
      "Action",
      "Crime",
      "Thriller"
    ],
    "posterTone": 2,
    "glyph": "V"
  }
];
